apiVersion: v1
kind: Pod
metadata:
  name: python-versions-pod
  labels:
    repo: apm-agent-python
spec:
  containers:
  - name: python-3-6
    image: python:3.6
    command:
    - sleep
    args:
    - infinity
