apiVersion: v1
kind: Pod
metadata:
  name: python-versions-pod
  labels:
    repo: apm-agent-python
spec:
  containers:
  - name: python-3-6
    image: python:3.6
    command:
    - sleep
    args:
    - infinity
  - name: python-3-7
    image: python:3.7
    command:
    - sleep
    args:
    - infinity
  - name: python-3-8
    image: python:3.8
    command:
    - sleep
    args:
    - infinity
  - name: python-3-9
    image: python:3.9
    command:
    - sleep
    args:
    - infinity
  - name: python-3-10
    image: python:3.10
    command:
    - sleep
    args:
    - infinity
