apiVersion: batch/v1
kind: Job
metadata:
  name: apm-agen-python-flask-2.0
  labels:
    repo: apm-agent-python
    type: unit-test
    framework: flask-2.0
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: python-3-6
        image: apm-agent-python-3.6
        command: [ "tests/scripts/run_tests.sh" ]
        env:
        - name: WEBFRAMEWORK
          value: "flask-2.0"
      - name: python-3-7
        image: apm-agent-python-3.7
        command: [ "tests/scripts/run_tests.sh" ]
        env:
        - name: WEBFRAMEWORK
          value: "flask-2.0"
      - name: python-3-8
        image: apm-agent-python-3.8
        command: [ "tests/scripts/run_tests.sh" ]
        env:
        - name: WEBFRAMEWORK
          value: "flask-2.0"
      - name: python-3-9
        image: apm-agent-python-3.9
        command: [ "tests/scripts/run_tests.sh" ]
        env:
        - name: WEBFRAMEWORK
          value: "flask-2.0"
      - name: python-3-10
        image: apm-agent-python-3.10
        command: [ "tests/scripts/run_tests.sh" ]
        env:
        - name: WEBFRAMEWORK
          value: "flask-2.0"
