apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: apm-agent-python
# The list of docker images to be built and in sync with the workspace by default
build:
  local:
    tryImportMissing: false
    concurrency: 0
  artifacts:
  # Skaffold requires a default artifacts so we can use profiles with a patch command
  # using the latest python version supported.
  - image: apm-agent-python-3.10
    context: .
    docker:
      dockerfile: ".k8s/Dockerfile"
      buildArgs:
        PYTHON_VERSION: "3.10"
deploy:
  kubectl:
    manifests:
    # Skaffold requires a default deploy so we can use profiles with a patch command.
    - ".k8s/generated/default.yaml"

profiles:
# Generated
